env:
  browser: true
  es2021: true
extends:
  - '@remix-run/eslint-config'
  - '@remix-run/eslint-config/node'
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
  - react
rules:
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
